void static tramplin_00() {panic_handler(0x00);}
void static tramplin_01() {panic_handler(0x01);}
void static tramplin_02() {panic_handler(0x02);}
void static tramplin_03() {panic_handler(0x03);}
void static tramplin_04() {panic_handler(0x04);}
void static tramplin_05() {panic_handler(0x05);}
void static tramplin_06() {panic_handler(0x06);}
void static tramplin_07() {panic_handler(0x07);}
void static tramplin_08() {panic_handler(0x08);}
void static tramplin_09() {panic_handler(0x09);}
void static tramplin_0A() {panic_handler(0x0A);}
void static tramplin_0B() {panic_handler(0x0B);}
void static tramplin_0C() {panic_handler(0x0C);}
void static tramplin_0D() {panic_handler(0x0D);}
void static tramplin_0E() {panic_handler(0x0E);}
void static tramplin_0F() {panic_handler(0x0F);}
void static tramplin_10() {panic_handler(0x10);}
void static tramplin_11() {panic_handler(0x11);}
void static tramplin_12() {panic_handler(0x12);}
void static tramplin_13() {panic_handler(0x13);}
void static tramplin_14() {panic_handler(0x14);}
void static tramplin_15() {panic_handler(0x15);}
void static tramplin_16() {panic_handler(0x16);}
void static tramplin_17() {panic_handler(0x17);}
void static tramplin_18() {panic_handler(0x18);}
void static tramplin_19() {panic_handler(0x19);}
void static tramplin_1A() {panic_handler(0x1A);}
void static tramplin_1B() {panic_handler(0x1B);}
void static tramplin_1C() {panic_handler(0x1C);}
void static tramplin_1D() {panic_handler(0x1D);}
void static tramplin_1E() {panic_handler(0x1E);}
void static tramplin_1F() {panic_handler(0x1F);}
void static tramplin_20() {panic_handler(0x20);}
void static tramplin_21() {panic_handler(0x21);}
void static tramplin_22() {panic_handler(0x22);}
void static tramplin_23() {panic_handler(0x23);}
void static tramplin_24() {panic_handler(0x24);}
void static tramplin_25() {panic_handler(0x25);}
void static tramplin_26() {panic_handler(0x26);}
void static tramplin_27() {panic_handler(0x27);}
void static tramplin_28() {panic_handler(0x28);}
void static tramplin_29() {panic_handler(0x29);}
void static tramplin_2A() {panic_handler(0x2A);}
void static tramplin_2B() {panic_handler(0x2B);}
void static tramplin_2C() {panic_handler(0x2C);}
void static tramplin_2D() {panic_handler(0x2D);}
void static tramplin_2E() {panic_handler(0x2E);}
void static tramplin_2F() {panic_handler(0x2F);}
void static tramplin_30() {panic_handler(0x30);}
void static tramplin_31() {panic_handler(0x31);}
void static tramplin_32() {panic_handler(0x32);}
void static tramplin_33() {panic_handler(0x33);}
void static tramplin_34() {panic_handler(0x34);}
void static tramplin_35() {panic_handler(0x35);}
void static tramplin_36() {panic_handler(0x36);}
void static tramplin_37() {panic_handler(0x37);}
void static tramplin_38() {panic_handler(0x38);}
void static tramplin_39() {panic_handler(0x39);}
void static tramplin_3A() {panic_handler(0x3A);}
void static tramplin_3B() {panic_handler(0x3B);}
void static tramplin_3C() {panic_handler(0x3C);}
void static tramplin_3D() {panic_handler(0x3D);}
void static tramplin_3E() {panic_handler(0x3E);}
void static tramplin_3F() {panic_handler(0x3F);}
void static tramplin_40() {panic_handler(0x40);}
void static tramplin_41() {panic_handler(0x41);}
void static tramplin_42() {panic_handler(0x42);}
void static tramplin_43() {panic_handler(0x43);}
void static tramplin_44() {panic_handler(0x44);}
void static tramplin_45() {panic_handler(0x45);}
void static tramplin_46() {panic_handler(0x46);}
void static tramplin_47() {panic_handler(0x47);}
void static tramplin_48() {panic_handler(0x48);}
void static tramplin_49() {panic_handler(0x49);}
void static tramplin_4A() {panic_handler(0x4A);}
void static tramplin_4B() {panic_handler(0x4B);}
void static tramplin_4C() {panic_handler(0x4C);}
void static tramplin_4D() {panic_handler(0x4D);}
void static tramplin_4E() {panic_handler(0x4E);}
void static tramplin_4F() {panic_handler(0x4F);}
void static tramplin_50() {panic_handler(0x50);}
void static tramplin_51() {panic_handler(0x51);}
void static tramplin_52() {panic_handler(0x52);}
void static tramplin_53() {panic_handler(0x53);}
void static tramplin_54() {panic_handler(0x54);}
void static tramplin_55() {panic_handler(0x55);}
void static tramplin_56() {panic_handler(0x56);}
void static tramplin_57() {panic_handler(0x57);}
void static tramplin_58() {panic_handler(0x58);}
void static tramplin_59() {panic_handler(0x59);}
void static tramplin_5A() {panic_handler(0x5A);}
void static tramplin_5B() {panic_handler(0x5B);}
void static tramplin_5C() {panic_handler(0x5C);}
void static tramplin_5D() {panic_handler(0x5D);}
void static tramplin_5E() {panic_handler(0x5E);}
void static tramplin_5F() {panic_handler(0x5F);}
void static tramplin_60() {panic_handler(0x60);}
void static tramplin_61() {panic_handler(0x61);}
void static tramplin_62() {panic_handler(0x62);}
void static tramplin_63() {panic_handler(0x63);}
void static tramplin_64() {panic_handler(0x64);}
void static tramplin_65() {panic_handler(0x65);}
void static tramplin_66() {panic_handler(0x66);}
void static tramplin_67() {panic_handler(0x67);}
void static tramplin_68() {panic_handler(0x68);}
void static tramplin_69() {panic_handler(0x69);}
void static tramplin_6A() {panic_handler(0x6A);}
void static tramplin_6B() {panic_handler(0x6B);}
void static tramplin_6C() {panic_handler(0x6C);}
void static tramplin_6D() {panic_handler(0x6D);}
void static tramplin_6E() {panic_handler(0x6E);}
void static tramplin_6F() {panic_handler(0x6F);}
void static tramplin_70() {panic_handler(0x70);}
void static tramplin_71() {panic_handler(0x71);}
void static tramplin_72() {panic_handler(0x72);}
void static tramplin_73() {panic_handler(0x73);}
void static tramplin_74() {panic_handler(0x74);}
void static tramplin_75() {panic_handler(0x75);}
void static tramplin_76() {panic_handler(0x76);}
void static tramplin_77() {panic_handler(0x77);}
void static tramplin_78() {panic_handler(0x78);}
void static tramplin_79() {panic_handler(0x79);}
void static tramplin_7A() {panic_handler(0x7A);}
void static tramplin_7B() {panic_handler(0x7B);}
void static tramplin_7C() {panic_handler(0x7C);}
void static tramplin_7D() {panic_handler(0x7D);}
void static tramplin_7E() {panic_handler(0x7E);}
void static tramplin_7F() {panic_handler(0x7F);}
void static tramplin_80() {panic_handler(0x80);}
void static tramplin_81() {panic_handler(0x81);}
void static tramplin_82() {panic_handler(0x82);}
void static tramplin_83() {panic_handler(0x83);}
void static tramplin_84() {panic_handler(0x84);}
void static tramplin_85() {panic_handler(0x85);}
void static tramplin_86() {panic_handler(0x86);}
void static tramplin_87() {panic_handler(0x87);}
void static tramplin_88() {panic_handler(0x88);}
void static tramplin_89() {panic_handler(0x89);}
void static tramplin_8A() {panic_handler(0x8A);}
void static tramplin_8B() {panic_handler(0x8B);}
void static tramplin_8C() {panic_handler(0x8C);}
void static tramplin_8D() {panic_handler(0x8D);}
void static tramplin_8E() {panic_handler(0x8E);}
void static tramplin_8F() {panic_handler(0x8F);}
void static tramplin_90() {panic_handler(0x90);}
void static tramplin_91() {panic_handler(0x91);}
void static tramplin_92() {panic_handler(0x92);}
void static tramplin_93() {panic_handler(0x93);}
void static tramplin_94() {panic_handler(0x94);}
void static tramplin_95() {panic_handler(0x95);}
void static tramplin_96() {panic_handler(0x96);}
void static tramplin_97() {panic_handler(0x97);}
void static tramplin_98() {panic_handler(0x98);}
void static tramplin_99() {panic_handler(0x99);}
void static tramplin_9A() {panic_handler(0x9A);}
void static tramplin_9B() {panic_handler(0x9B);}
void static tramplin_9C() {panic_handler(0x9C);}
void static tramplin_9D() {panic_handler(0x9D);}
void static tramplin_9E() {panic_handler(0x9E);}
void static tramplin_9F() {panic_handler(0x9F);}
void static tramplin_A0() {panic_handler(0xA0);}
void static tramplin_A1() {panic_handler(0xA1);}
void static tramplin_A2() {panic_handler(0xA2);}
void static tramplin_A3() {panic_handler(0xA3);}
void static tramplin_A4() {panic_handler(0xA4);}
void static tramplin_A5() {panic_handler(0xA5);}
void static tramplin_A6() {panic_handler(0xA6);}
void static tramplin_A7() {panic_handler(0xA7);}
void static tramplin_A8() {panic_handler(0xA8);}
void static tramplin_A9() {panic_handler(0xA9);}
void static tramplin_AA() {panic_handler(0xAA);}
void static tramplin_AB() {panic_handler(0xAB);}
void static tramplin_AC() {panic_handler(0xAC);}
void static tramplin_AD() {panic_handler(0xAD);}
void static tramplin_AE() {panic_handler(0xAE);}
void static tramplin_AF() {panic_handler(0xAF);}
void static tramplin_B0() {panic_handler(0xB0);}
void static tramplin_B1() {panic_handler(0xB1);}
void static tramplin_B2() {panic_handler(0xB2);}
void static tramplin_B3() {panic_handler(0xB3);}
void static tramplin_B4() {panic_handler(0xB4);}
void static tramplin_B5() {panic_handler(0xB5);}
void static tramplin_B6() {panic_handler(0xB6);}
void static tramplin_B7() {panic_handler(0xB7);}
void static tramplin_B8() {panic_handler(0xB8);}
void static tramplin_B9() {panic_handler(0xB9);}
void static tramplin_BA() {panic_handler(0xBA);}
void static tramplin_BB() {panic_handler(0xBB);}
void static tramplin_BC() {panic_handler(0xBC);}
void static tramplin_BD() {panic_handler(0xBD);}
void static tramplin_BE() {panic_handler(0xBE);}
void static tramplin_BF() {panic_handler(0xBF);}
void static tramplin_C0() {panic_handler(0xC0);}
void static tramplin_C1() {panic_handler(0xC1);}
void static tramplin_C2() {panic_handler(0xC2);}
void static tramplin_C3() {panic_handler(0xC3);}
void static tramplin_C4() {panic_handler(0xC4);}
void static tramplin_C5() {panic_handler(0xC5);}
void static tramplin_C6() {panic_handler(0xC6);}
void static tramplin_C7() {panic_handler(0xC7);}
void static tramplin_C8() {panic_handler(0xC8);}
void static tramplin_C9() {panic_handler(0xC9);}
void static tramplin_CA() {panic_handler(0xCA);}
void static tramplin_CB() {panic_handler(0xCB);}
void static tramplin_CC() {panic_handler(0xCC);}
void static tramplin_CD() {panic_handler(0xCD);}
void static tramplin_CE() {panic_handler(0xCE);}
void static tramplin_CF() {panic_handler(0xCF);}
void static tramplin_D0() {panic_handler(0xD0);}
void static tramplin_D1() {panic_handler(0xD1);}
void static tramplin_D2() {panic_handler(0xD2);}
void static tramplin_D3() {panic_handler(0xD3);}
void static tramplin_D4() {panic_handler(0xD4);}
void static tramplin_D5() {panic_handler(0xD5);}
void static tramplin_D6() {panic_handler(0xD6);}
void static tramplin_D7() {panic_handler(0xD7);}
void static tramplin_D8() {panic_handler(0xD8);}
void static tramplin_D9() {panic_handler(0xD9);}
void static tramplin_DA() {panic_handler(0xDA);}
void static tramplin_DB() {panic_handler(0xDB);}
void static tramplin_DC() {panic_handler(0xDC);}
void static tramplin_DD() {panic_handler(0xDD);}
void static tramplin_DE() {panic_handler(0xDE);}
void static tramplin_DF() {panic_handler(0xDF);}
void static tramplin_E0() {panic_handler(0xE0);}
void static tramplin_E1() {panic_handler(0xE1);}
void static tramplin_E2() {panic_handler(0xE2);}
void static tramplin_E3() {panic_handler(0xE3);}
void static tramplin_E4() {panic_handler(0xE4);}
void static tramplin_E5() {panic_handler(0xE5);}
void static tramplin_E6() {panic_handler(0xE6);}
void static tramplin_E7() {panic_handler(0xE7);}
void static tramplin_E8() {panic_handler(0xE8);}
void static tramplin_E9() {panic_handler(0xE9);}
void static tramplin_EA() {panic_handler(0xEA);}
void static tramplin_EB() {panic_handler(0xEB);}
void static tramplin_EC() {panic_handler(0xEC);}
void static tramplin_ED() {panic_handler(0xED);}
void static tramplin_EE() {panic_handler(0xEE);}
void static tramplin_EF() {panic_handler(0xEF);}
void static tramplin_F0() {panic_handler(0xF0);}
void static tramplin_F1() {panic_handler(0xF1);}
void static tramplin_F2() {panic_handler(0xF2);}
void static tramplin_F3() {panic_handler(0xF3);}
void static tramplin_F4() {panic_handler(0xF4);}
void static tramplin_F5() {panic_handler(0xF5);}
void static tramplin_F6() {panic_handler(0xF6);}
void static tramplin_F7() {panic_handler(0xF7);}
void static tramplin_F8() {panic_handler(0xF8);}
void static tramplin_F9() {panic_handler(0xF9);}
void static tramplin_FA() {panic_handler(0xFA);}
void static tramplin_FB() {panic_handler(0xFB);}
void static tramplin_FC() {panic_handler(0xFC);}
void static tramplin_FD() {panic_handler(0xFD);}
void static tramplin_FE() {panic_handler(0xFE);}
void static tramplin_FF() {panic_handler(0xFF);}
static void** tramplins = {tramplin_00, tramplin_01, tramplin_02, tramplin_03, tramplin_04, tramplin_05, tramplin_06, tramplin_07, tramplin_08, tramplin_09, tramplin_0A, tramplin_0B, tramplin_0C, tramplin_0D, tramplin_0E, tramplin_0F, tramplin_10, tramplin_11, tramplin_12, tramplin_13, tramplin_14, tramplin_15, tramplin_16, tramplin_17, tramplin_18, tramplin_19, tramplin_1A, tramplin_1B, tramplin_1C, tramplin_1D, tramplin_1E, tramplin_1F, tramplin_20, tramplin_21, tramplin_22, tramplin_23, tramplin_24, tramplin_25, tramplin_26, tramplin_27, tramplin_28, tramplin_29, tramplin_2A, tramplin_2B, tramplin_2C, tramplin_2D, tramplin_2E, tramplin_2F, tramplin_30, tramplin_31, tramplin_32, tramplin_33, tramplin_34, tramplin_35, tramplin_36, tramplin_37, tramplin_38, tramplin_39, tramplin_3A, tramplin_3B, tramplin_3C, tramplin_3D, tramplin_3E, tramplin_3F, tramplin_40, tramplin_41, tramplin_42, tramplin_43, tramplin_44, tramplin_45, tramplin_46, tramplin_47, tramplin_48, tramplin_49, tramplin_4A, tramplin_4B, tramplin_4C, tramplin_4D, tramplin_4E, tramplin_4F, tramplin_50, tramplin_51, tramplin_52, tramplin_53, tramplin_54, tramplin_55, tramplin_56, tramplin_57, tramplin_58, tramplin_59, tramplin_5A, tramplin_5B, tramplin_5C, tramplin_5D, tramplin_5E, tramplin_5F, tramplin_60, tramplin_61, tramplin_62, tramplin_63, tramplin_64, tramplin_65, tramplin_66, tramplin_67, tramplin_68, tramplin_69, tramplin_6A, tramplin_6B, tramplin_6C, tramplin_6D, tramplin_6E, tramplin_6F, tramplin_70, tramplin_71, tramplin_72, tramplin_73, tramplin_74, tramplin_75, tramplin_76, tramplin_77, tramplin_78, tramplin_79, tramplin_7A, tramplin_7B, tramplin_7C, tramplin_7D, tramplin_7E, tramplin_7F, tramplin_80, tramplin_81, tramplin_82, tramplin_83, tramplin_84, tramplin_85, tramplin_86, tramplin_87, tramplin_88, tramplin_89, tramplin_8A, tramplin_8B, tramplin_8C, tramplin_8D, tramplin_8E, tramplin_8F, tramplin_90, tramplin_91, tramplin_92, tramplin_93, tramplin_94, tramplin_95, tramplin_96, tramplin_97, tramplin_98, tramplin_99, tramplin_9A, tramplin_9B, tramplin_9C, tramplin_9D, tramplin_9E, tramplin_9F, tramplin_A0, tramplin_A1, tramplin_A2, tramplin_A3, tramplin_A4, tramplin_A5, tramplin_A6, tramplin_A7, tramplin_A8, tramplin_A9, tramplin_AA, tramplin_AB, tramplin_AC, tramplin_AD, tramplin_AE, tramplin_AF, tramplin_B0, tramplin_B1, tramplin_B2, tramplin_B3, tramplin_B4, tramplin_B5, tramplin_B6, tramplin_B7, tramplin_B8, tramplin_B9, tramplin_BA, tramplin_BB, tramplin_BC, tramplin_BD, tramplin_BE, tramplin_BF, tramplin_C0, tramplin_C1, tramplin_C2, tramplin_C3, tramplin_C4, tramplin_C5, tramplin_C6, tramplin_C7, tramplin_C8, tramplin_C9, tramplin_CA, tramplin_CB, tramplin_CC, tramplin_CD, tramplin_CE, tramplin_CF, tramplin_D0, tramplin_D1, tramplin_D2, tramplin_D3, tramplin_D4, tramplin_D5, tramplin_D6, tramplin_D7, tramplin_D8, tramplin_D9, tramplin_DA, tramplin_DB, tramplin_DC, tramplin_DD, tramplin_DE, tramplin_DF, tramplin_E0, tramplin_E1, tramplin_E2, tramplin_E3, tramplin_E4, tramplin_E5, tramplin_E6, tramplin_E7, tramplin_E8, tramplin_E9, tramplin_EA, tramplin_EB, tramplin_EC, tramplin_ED, tramplin_EE, tramplin_EF, tramplin_F0, tramplin_F1, tramplin_F2, tramplin_F3, tramplin_F4, tramplin_F5, tramplin_F6, tramplin_F7, tramplin_F8, tramplin_F9, tramplin_FA, tramplin_FB, tramplin_FC, tramplin_FD, tramplin_FE, tramplin_FF}
